In [1]:
import numpy as np

inputs = np.array([[2],[3]])

w_h1 = np.array([0.12, 0.23])
w_h2 = np.array([0.13, 0.10])
w_l1 = np.stack([w_h1, w_h2],axis=0)
w_out = np.array([0.17, 0.17])
z1 = np.dot(w_l1, inputs)
out = np.dot(w_out, z1)
display(w_l1, z1, out)

array([[0.12, 0.23],
       [0.13, 0.1 ]])

array([[0.93],
       [0.56]])

array([0.2533])

time: 62.6 ms (started: 2021-12-27 06:53:16 +00:00)


In [2]:
learn_rate = 0.05
epoch = 20
for i in range(1,epoch+1):
    loss = out-1
    w_l1 = w_l1-learn_rate*loss*inputs*w_out
    w_out = w_out-learn_rate*loss*z1.reshape(-1)
    z1 = np.dot(w_l1, inputs)
    out = np.dot(w_out, z1)
    print(out, i)
    
# print(f"w1 = {w_l1[0,0]}, w2 = {w_l1[0,1]}, w3 = {w_l1[1,0]}, w4 = {w_l1[1,1]}, w5 = {w_out[0]}, w6 = {w_out[1]}")

[0.32846809] 1
[0.412788] 2
[0.5031445] 3
[0.59473204] 4
[0.6819189] 5
[0.75961477] 6
[0.82452077] 7
[0.87564336] 8
[0.91394494] 9
[0.94151751] 10
[0.96077555] 11
[0.97393469] 12
[0.98278908] 13
[0.98868439] 14
[0.99258168] 15
[0.99514591] 16
[0.99682775] 17
[0.99792858] 18
[0.99864812] 19
[0.99911803] 20
time: 6 ms (started: 2021-12-27 06:53:16 +00:00)


In [3]:
w1 = 0.12
w2 = 0.23
w3 = 0.13
w4 = 0.10
w5 = 0.17
w6 = 0.17
input1 = 2
input2 = 3
actual = 1
h1 = (w1 * input1) + (w2 * input2)
h2 = (w3 * input1) + (w4 * input2)
prediction = w5 * h1 + w6 *h2
print(h1, h2, prediction)

0.93 0.56 0.2533
time: 810 µs (started: 2021-12-27 06:53:16 +00:00)
