In [38]:
import numpy as np

inputs = np.array([[2],[3]])

w_h1 = np.array([0.12, 0.23])
w_h2 = np.array([0.13, 0.10])
w_l1 = np.stack([w_h1, w_h2],axis=0)
w_out = np.array([0.17, 0.17])
z1 = np.dot(w_l1, inputs)
out = np.dot(w_out, z1)
display(w_l1, z1, out)

array([[0.12, 0.23],
       [0.13, 0.1 ]])

array([[0.93],
       [0.56]])

array([0.2533])

In [39]:
learn_rate = 0.05
epoch = 20
for i in range(1,epoch+1):
    loss = out-1
    w_out = w_out-learn_rate*loss*z1.reshape(-1)
    w_l1 = w_l1-learn_rate*loss*inputs*w_out
    z1 = np.dot(w_l1, inputs)
    out = np.dot(w_out, z1)
    print(out, i)
    
# print(f"w1 = {w_l1[0,0]}, w2 = {w_l1[0,1]}, w3 = {w_l1[1,0]}, w4 = {w_l1[1,1]}, w5 = {w_out[0]}, w6 = {w_out[1]}")

[0.3333145] 1
[0.42335661] 2
[0.51920946] 3
[0.61479954] 4
[0.70360506] 5
[0.7804411] 6
[0.84266825] 7
[0.89027026] 8
[0.92504654] 9
[0.94957687] 10
[0.96644325] 11
[0.9778333] 12
[0.98543068] 13
[0.99045623] 14
[0.99376213] 15
[0.99592884] 16
[0.9973455] 17
[0.99827028] 18
[0.99887334] 19
[0.99926634] 20


In [3]:
w1 = 0.12
w2 = 0.23
w3 = 0.13
w4 = 0.10
w5 = 0.17
w6 = 0.17
input1 = 2
input2 = 3
actual = 1
h1 = (w1 * input1) + (w2 * input2)
h2 = (w3 * input1) + (w4 * input2)
prediction = w5 * h1 + w6 *h2
print(h1, h2, prediction)

0.93 0.56 0.2533
