### Introduction to Machine Learning @ NCCU.EDU.TW
##### prepared by Chao-Lin Liu

In [1]:
list1 = [1, 2, 3]
list2 = [2, 3, 4]

In [2]:
list3 = list1-list2

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [3]:
import numpy as np

In [4]:
v1 = np.array([1, 2, 3])

In [5]:
v2 = np.array([4,5,6])

In [7]:
v3 = v2 - v1

In [8]:
print (v3)

[3 3 3]


In [9]:
v1*v2

array([ 4, 10, 18])

In [10]:
def cool (v1, v2):
    return v1*v2

In [11]:
v32 = cool(v1, v2)

In [12]:
v32

array([ 4, 10, 18])

In [13]:
v4=np.array([1,3,5])

In [14]:
v4 = v1 + 1

In [15]:
v4

array([2, 3, 4])

In [17]:
m1 = np.array([[1,2,3],[4,5,6]])

In [18]:
m1.shape

(2, 3)

In [19]:
m2 = np.array([[1,2],[3,4],[5,6]])

$m1 = \begin{bmatrix}1 & 2 & 3\\4 & 5 & 6\end{bmatrix}$
$m2 = \begin{bmatrix}1 & 2\\3 & 4\\5  & 6\end{bmatrix}$

In [20]:
m1*m2

ValueError: ignored

In [21]:
np.dot(m1,m2)

array([[22, 28],
       [49, 64]])

In [22]:
m3 = m1.T

In [23]:
m3

array([[1, 4],
       [2, 5],
       [3, 6]])

In [24]:
woo = np.sin(m3)

In [25]:
woo

array([[ 0.84147098, -0.7568025 ],
       [ 0.90929743, -0.95892427],
       [ 0.14112001, -0.2794155 ]])