#### Introduction to Machine Learning
#### 國立政治大學資訊科學系劉昭麟

$$
x = \begin{bmatrix} x_1 \\ x_2 \end{bmatrix} $$
$$
w = \begin{bmatrix} w_{10}\ \ w_{11}\ \ w_{12} \\  w_{20}\ \ w_{21}\ \ w_{22} \end{bmatrix} 
$$
$$
a = \begin{bmatrix} a_0 \\ a_1 \\ a_2\end{bmatrix}, \ a_0=1 $$
$$ x=wa \Rightarrow \begin{bmatrix} x_1 \\ x_2 \end{bmatrix}=\begin{bmatrix} w_{10}\ \ w_{11}\ \ w_{12} \\  w_{20}\ \ w_{21}\ \ w_{22} \end{bmatrix}\begin{bmatrix} a_0 \\ a_1 \\ a_2\end{bmatrix} = \begin{bmatrix} w_{10}a_0+w_{11}a_1+w_{12}a_2 \\  w_{20}a_0+w_{21}a_1+w_{22}a_2 \end{bmatrix}$$

In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
import pandas as pd
import numpy as np

##### 以上式子是 DM4 的形式；以下的符號有一些改變
##### 以下的 Y 是上面的 x
##### 以下的 X 是上面的 a

In [2]:
df = pd.read_csv("multivariates2.csv")

In [3]:
df[0:5]

X1        X2        Y1        Y2
0  4.575751  5.554888  3.032127  4.562959
1 -4.976465 -5.130944  1.621339  3.877591
2  1.112631 -1.671880  4.076308  4.613840
3  0.429415  8.870211  0.858427  0.283946
4 -4.759230  7.055329 -0.780824 -4.170175

In [4]:
#lr_XX = np.asarray([[i,j] for i, j in zip(df['X1'].values, df['X2'].values)])
features = ['X1','X2']
lr_XX = df[features].to_numpy()
lr_XX[0:5]

array([[ 4.57575082,  5.55488768],
       [-4.97646529, -5.13094402],
       [ 1.11263147, -1.67187952],
       [ 0.4294147 ,  8.87021061],
       [-4.7592295 ,  7.05532927]])

In [5]:
#lr_yy = df['Y'].values
#lr_yy = np.asarray([[i,j] for i, j in zip(df['Y1'].values, df['Y2'].values)])
targets = ['Y1', 'Y2']
lr_yy = df[targets].to_numpy()
lr_yy[0:5]

array([[ 3.03212748,  4.56295925],
       [ 1.62133912,  3.87759121],
       [ 4.07630808,  4.6138401 ],
       [ 0.85842716,  0.28394586],
       [-0.78082446, -4.17017508]])

In [6]:
lr_XX_train = lr_XX[:-20]
lr_XX_test  = lr_XX[-20:]
lr_yy_train = lr_yy[:-20]
lr_yy_test  = lr_yy[-20:]

In [9]:
# Create linear regression object
regr = linear_model.LinearRegression()

# Train the model using the training sets
regr.fit(lr_XX_train, lr_yy_train)

# Make predictions using the testing set
lr_yy_pred = regr.predict(lr_XX_test)

# The coefficients
print('Coefficients: \n', regr.coef_)

# intercept
print('Intercept: \n', regr.intercept_)

# The mean squared error
print("Mean squared error: %.2f"
      % mean_squared_error(lr_yy_test, lr_yy_pred))
# Explained variance score: 1 is perfect prediction
print('Variance score: %.2f' % r2_score(lr_yy_test, lr_yy_pred))

# Plot outputs
#plt.scatter(lr_XX_test, lr_yy_test,  color='black')
#plt.plot(lr_XX_test, lr_yy_pred, color='blue', linewidth=3)

#plt.xticks(())
#plt.yticks(())

#plt.show()

Coefficients: 
 [[ 0.2903248  -0.20389607]
 [ 0.59615391 -0.48643619]]
Intercept: 
 [3.12544457 3.27786415]
Mean squared error: 0.84
Variance score: 0.88
