In [2]:
%matplotlib inline
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("multivariables43.csv")

In [5]:
df[0:5]

x1        x2        x3         y1         y2         y3        y4
0 -3.347854  0.637225  0.993636 -10.259299  15.757963 -11.531241  6.091132
1 -2.294942 -3.835492  1.310528 -10.533311  11.038025  10.425651 -1.378098
2 -3.196662 -2.017505 -0.086308 -15.131171  15.582931  -0.960921  1.914634
3  4.980073 -0.347092 -2.012394  23.598952 -22.271864   2.678937 -3.557890
4 -3.437117 -1.515536  2.608372 -10.563096  15.815291  -0.020831  3.266095

In [7]:
features = ['x1','x2','x3']
lr_XX = df[features].to_numpy()
lr_XX[0:5]

array([[-3.34785374,  0.63722465,  0.99363567],
       [-2.29494241, -3.83549233,  1.3105279 ],
       [-3.19666176, -2.01750513, -0.0863079 ],
       [ 4.98007281, -0.34709164, -2.01239398],
       [-3.43711728, -1.51553564,  2.60837192]])

In [9]:
targets = ['y1','y2','y3','y4']
lr_yy = df[targets].to_numpy()
lr_yy[0:5]

array([[-1.02592993e+01,  1.57579633e+01, -1.15312415e+01,
         6.09113153e+00],
       [-1.05333112e+01,  1.10380254e+01,  1.04256506e+01,
        -1.37809814e+00],
       [-1.51311705e+01,  1.55829309e+01, -9.60921427e-01,
         1.91463413e+00],
       [ 2.35989516e+01, -2.22718639e+01,  2.67893708e+00,
        -3.55789008e+00],
       [-1.05630957e+01,  1.58152909e+01, -2.08307620e-02,
         3.26609520e+00]])

In [10]:
lr_XX_train = lr_XX[:-20]
lr_XX_test  = lr_XX[-20:]
lr_yy_train = lr_yy[:-20]
lr_yy_test  = lr_yy[-20:]

In [11]:
# Create linear regression object
regr = linear_model.LinearRegression()

# Train the model using the training sets
regr.fit(lr_XX_train, lr_yy_train)

# Make predictions using the testing set
lr_yy_pred = regr.predict(lr_XX_test)

# The coefficients
print('Coefficients: \n', regr.coef_)

# intercept
print('Intercept: \n', regr.intercept_)

# The mean squared error
print("Mean squared error: %.2f"
      % mean_squared_error(lr_yy_test, lr_yy_pred))
# Explained variance score: 1 is perfect prediction
print('Variance score: %.2f' % r2_score(lr_yy_test, lr_yy_pred))

# Plot outputs
#plt.scatter(lr_XX_test, lr_yy_test,  color='black')
#plt.plot(lr_XX_test, lr_yy_pred, color='blue', linewidth=3)

#plt.xticks(())
#plt.yticks(())

#plt.show()

Coefficients: 
 [[ 4.90423496  1.34906377  1.88153572]
 [-4.69012254 -0.07141709 -0.31898284]
 [ 1.66027645 -4.42462051  1.32124705]
 [-0.93323695  1.46061848  0.14616697]]
Intercept: 
 [ 3.43014434  0.41858045 -4.46623968  1.89081189]
Mean squared error: 0.00
Variance score: 1.00


In [13]:
x = np.array([[0.9], [1.1], [2.1]])
y = np.array([0.9, 1.1, 1.9])
regr = linear_model.LinearRegression()

# Train the model using the training sets
regr.fit(x, y)

# The coefficients
print('Coefficients: \n', regr.coef_)

# intercept
print('Intercept: \n', regr.intercept_)


Coefficients: 
 [0.82258065]
Intercept: 
 0.17580645161290365


In [17]:
from math import log2

-1*4*((1/4)*log2(1/4))

2.0

In [18]:
-1*((1/10)*log2(1/10) + (2/10)*log2(2/10) + (3/10)*log2(3/10) + (4/10)*log2(4/10))

1.8464393446710154

In [19]:
-1*((1/2)*log2(1/2) + (1/2)*log2(1/2) )

1.0

In [20]:
-1*((2/14)*log2(2/14) + (4/14)*log2(4/14) + (8/14)*log2(8/14) )

1.3787834934861753

In [22]:
-1*( (6/14)*log2(6/14) + (8/14)*log2(8/14) )

0.9852281360342515